services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: resumes
      DATABASE_URL: postgresql://resume:secret@db/resumes