name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    services:
      db: #  ← this hostname MUST be “db”
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: resume
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: resumes
        options: >-
          --health-cmd="pg_isready -U resume -d resumes"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
        DATABASE_URL: postgresql://resume:secret@db/resumes
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r backend/requirements.txt pytest

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h db -U resume && break -U resume && break
            echo "🏃 waiting for PG ($i)…"
            sleep 2
          done

      - name: Init db schema
        run: psql "$DATABASE_URL" -f backend/sql/001_init.sql

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q