name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    services:
      db: #  ← this hostname MUST be “db”
        image: pgvector/pgvector:pg16
        ports: ["6572:5432"]
        env:
          POSTGRES_USER: resume
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: resumes
        options: >-
          --health-cmd="pg_isready -U resume -d resumes"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
        DATABASE_URL: postgresql://resume:secret@db/resumes?sslmode=disable
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r backend/requirements.txt pytest

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h db -U resume && break -U resume && break
            echo "🏃 waiting for PG ($i)…"
            sleep 2
          done

      - name: Init db schema
        env:
          PGPASSWORD: secret
        run: psql -h 127.0.0.1 -p 6572 -U resume -d resumes -c '\l'

      - name: Run tests
        run: pytest --cov=backend --cov-fail-under=80 -q
