name: db-ping
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    services:
      db:
        image: pgvector/pgvector:pg16
        ports: ["6572:5432"]
        env:
          POSTGRES_USER: resume
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: resumes
    steps:
      - name: Show db logs if it crashed
        if: failure()    # this runs only when a previous step fails
        run: docker logs $(docker ps -aqf "name=db") | tail -n 50
      - name: Ping DB
        run: psql "postgresql://resume:secret@localhost:6572/resumes?sslmode=disable" -c '\l'

      - name: Show db logs
        if: failure()
        run: docker logs $(docker ps -q -f "name=db") | tail -n 50
