name: db-ping
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    services:
      db:
        image: pgvector/pgvector:pg16
        ports: ["8098:5432"]
        env:
          POSTGRES_USER: resume
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: resumes
    steps:
      - name: Ping DB
        run: psql "postgresql://resume:secret@localhost:8098/resumes" -c '\l'
